# The following parameters are used to load the dataset
train_data: ./data/kg_train_dev.json
test_data: ./data/kg_test.json

# Training parameters
train:
  project_name: Entity KG
  model_names: [SAGE, GCN, GAT, SuperGAT]
  out_channels: 32
  learning_rate: 0.005
  num_epochs: 250
  weight_decay: 0.05

hf_token: ...