# The following parameters are used to load the dataset
data: ./data/kg_full_03-06-2024.json

# The following parameters are used to split the dataset into train, validation, and test sets
splitted_node_kwargs:
  split: train_rest
  num_val: 0.2
  num_test: 0.2

# Training parameters
train:
  project_name: Entity KG
  model_names: [SAGE, GCN, GAT, SuperGAT]
  learning_rate: 0.005
  num_epochs: 250
  weight_decay: 0.05

hf_token: ...